---
- name: Hello Events
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Say Hello
      condition: event.payload.message == "test"
      action:
#        run_job_template:
        run_workflow_template 
#          name: Demo Job Template
          name: wf_webhook
          organization: Default
#        run_job_template:
#          name: Demo Job Template2
#          organization: Default
#      action:
#        run_workflow_template:
#          name: wf
#          organization: Default
#          job_args:
#            extra_vars:
#              instance_type: "value"
#        debug:
#          msg: "Rule fired successfully"
